import { serve } from "https://deno.land/std@0.190.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Content-Type': 'application/json',
}

// NOTE: This function must be called with the Service Role Key to bypass RLS and update the profile.
// In a real scenario, this would be called by a payment webhook, not the client.
// For this simulation, we use a short-lived token generated by create-checkout.

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    if (req.method !== 'POST') {
      return new Response(JSON.stringify({ error: 'Method not allowed' }), { status: 405, headers: corsHeaders })
    }

    const body = await req.json().catch(() => ({}));
    const { user_id, token } = body;

    if (!user_id || !token) {
      return new Response(JSON.stringify({ error: 'Missing user_id or token' }), { status: 400, headers: corsHeaders })
    }

    // 1. Verify the short-lived token (Simulated verification: check if token matches expected format)
    // In a real scenario, this token would be checked against a database record or a JWT signature.
    // For this simulation, we check if the token is a valid UUID-like string prefixed with 'premium_'.
    if (!token.startsWith('premium_') || token.length < 20) {
        return new Response(JSON.stringify({ error: 'Invalid or expired token' }), { status: 403, headers: corsHeaders });
    }
    
    // 2. Use Service Role Key to update the profile (Bypasses RLS)
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // Set is_premium = true and clear any pending trial end date
    const { error: updateError } = await supabaseAdmin
      .from('profiles')
      .update({ is_premium: true, trial_ends_at: null })
      .eq('id', user_id);

    if (updateError) {
      throw updateError;
    }

    // 3. Invalidate the token (Simulated: In a real app, delete the token from a temporary table here)
    
    return new Response(JSON.stringify({ message: 'Premium activated successfully' }), { status: 200, headers: corsHeaders });
  } catch (error) {
    console.error('activate-premium error:', error);
    return new Response(JSON.stringify({ error: String(error?.message ?? error) }), { status: 500, headers: corsHeaders });
  }
});